Repository acm-ucr/bitByBIT, pull requests merged in 2023-04, with the labels that each got.

#117 Create Profile Information Component
  components/Profile.jsx
Labels: Ready for Review, Profile

#116 Fix screen height on ProblemDescription
  components/ProblemDescription.jsx
Labels: Problems

#119 Improved Solutions Tab
  components/ProblemSolution.jsx
  components/ProblemStateToggle.jsx
  pages/problems.js
Labels: Ready for Review, Problems

#132 Optimized Bootstrap Imports
  components/Navigation.jsx
  pages/dashboard.js
  pages/index.js
  pages/profile.js
Labels: Ready for Review, Repository

#131 Map Through Problems Category
  components/ProblemsSolved.jsx
Labels: Ready for Review, Problems

#129 Used next/image for primaryLogo
  components/PrimaryLogo.jsx
Labels: Ready for Review

#134 Create UserContext
  components/UserContext.jsx
  components/Welcome.jsx
  package-lock.json
  package.json
  pages/_app.js
  pages/api/getUserInfo.js
Labels: Ready for Review, Repository

#133 Mapped through filters
  components/Filters.jsx
  pages/dashboard.js
Labels: Dashboard, Ready for Review

#135 Add Build Check
  .github/workflows/main.yaml
Labels: Ready for Review, Repository

#137 break down entry and delete stuff
  components/ProblemSolution.jsx
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
Labels: Ready for Review

#149 Removed search bar and random button
  components/Search.jsx
  package-lock.json
  package.json
  pages/dashboard.js
Labels: Dashboard, Ready for Review

#151 Archive Heatmap
  components/archive/Submissions.jsx
  pages/profile.js
Labels: Ready for Review, Profile

#152 Console Component
  components/Console.jsx
Labels: Ready for Review, Problems

#153 moved up filters
  components/ProblemRecord.jsx
  components/ProblemsCategory.jsx
Labels: Dashboard, Ready for Review

#160 populated profile component with user context
  pages/profile.js
Labels: Ready for Review, Profile

#161 fix join date prop in profile component
  pages/profile.js
Labels: Ready for Review, Profile

#168 added filtering
  components/ProblemRecord.jsx
Labels: Ready for Review, Problems
