Repository acm-ucr/bitByBIT, pull requests merged in 2023-03, with the labels that each got.

#92 Add filter toggle functionality
  components/Filter.jsx
  components/Filters.jsx
Labels: Dashboard

#91 Remove side scrolling on Dashboard page
  pages/dashboard.js
Labels: Dashboard

#95 Put the Search Icon After the Text Field
  components/Search.jsx
Labels: Dashboard, Ready for Review

#94 Remove X After Each Tag
  components/Filter.jsx
Labels: Ready for Review, Problems

#93 Implement Problem Records
  components/ProblemRecord.jsx
  components/ProgressCircle.jsx
Labels: Ready for Review, Profile

#96 Fix Warnings
  pages/404.js
  pages/500.js
Labels: Ready for Review, Repository

#97 Change Progress Implementation
  components/Progress.jsx
  package-lock.json
  package.json
  pages/dashboard.js
  tailwind.config.js
Labels: Dashboard

#107 Jyro88/3 dots
  components/Problems.jsx
  components/Welcome.jsx
Labels: Ready for Review

#106 Used Readex for Welcome Page
  components/Welcome.jsx
Labels: Landing, Ready for Review

#104 Fix Nav Bar Hover
  components/Navigation.jsx
Labels: Ready for Review, Navigation

#102 changed the hover of search to be green
  components/Search.jsx
Labels: Dashboard, Ready for Review

#103 Create Problem Description
  components/ProblemDescription.jsx
Labels: Ready for Review, Problems

#100 Sreeja pagireddy/container
  components/Filters.jsx
  components/Search.jsx
Labels: Ready for Review, Problems

#99 hover white text
  components/Filters.jsx
  components/Search.jsx
Labels: Ready for Review, Problems

#105 Update Landing
  components/Welcome.jsx
Labels: Landing, Ready for Review

#115 Implement Clear All Functionality
  components/Filter.jsx
  components/Filters.jsx
Labels: Dashboard, Ready for Review
