Repository acm-ucr/bitByBIT, pull requests merged in 2023-08, with the labels that each got.

#309 Reroute logged-in user to dashboard
  components/ProtectedPage.jsx
  pages/index.js
Labels: Dashboard, Do Not Merge, Navigation

#319 Added hover effect on filter components
  components/Filter.jsx
  pages/user/dashboard.js
Labels: Dashboard, Ready for Review

#316 Add Boilerplate code to CodeEditor
  components/CodeEditor.jsx
  pages/user/problems/[id].js
Labels: Ready for Review, Problems

#320 fixed new userName update
  components/Profile.jsx
  pages/api/auth/[...nextauth].js
  pages/api/updateUserInfo.js
Labels: Ready for Review, Profile

#326 Changed default language to Python
  pages/_app.js
Labels: Ready for Review, Problems

#325 Styled loading screen
  components/LoadingScreen.jsx
  components/ProtectedPage.jsx
Labels: Dashboard, Ready for Review

#324 Fix Welcome Height
  pages/index.js
Labels: Landing, Ready for Review

#331 Redirect invalid problem id to 404 page
  pages/user/problems/[id].js
Labels: Ready for Review, Problems

#333 fixed new user login
  pages/api/auth/[...nextauth].js
  pages/user/problems/[id].js
Labels: Auth

#336 Cached problems in local storage
  pages/user/dashboard.js
Labels: Dashboard, Ready for Review

#337 Seanquiambao/code mirror python
  components/CodeEditor.jsx
Labels: Ready for Review, Problems

#340 fixed problem record
  components/ProblemRecord.jsx
Labels: Profile

#330 Fix Results Component
  components/Results.jsx
Labels: Ready for Review, Problems

#359 Fixed Tags Parsing Error
  components/ProblemDescription.jsx
  components/ProgrammingProblem.jsx
Labels: Ready for Review, Repository

#360 Remove Solution Tab
  components/ProblemStateToggle.jsx
  components/ProgrammingProblem.jsx
Labels: Ready for Review, Problems

#358 Added loading states in problem page
  pages/user/problems/[id].js
Labels: Ready for Review, Problems

#357 Fixed duplicate key and missing unique key errors
  components/Problems.jsx
  components/ProgrammingProblem.jsx
Labels: Dashboard, Ready for Review

#362 fixed ProgrammingProblem index
  components/ProgrammingProblem.jsx
Labels: Dashboard
