Repository acm-ucr/bitByBIT, pull requests merged in 2023-07, with the labels that each got.

#255 Fixed height issue on Profile page
  components/ProblemRecord.jsx
  pages/profile.js
Labels: Ready for Review, Profile

#257 Test Cases
  components/Console.jsx
  components/TestCases.jsx
Labels: Ready for Review, Problems

#258 format fixes
  pages/404.js
  pages/500.js
Labels: Ready for Review, Navigation

#256 Results Component
  components/Console.jsx
  components/Results.jsx
Labels: Ready for Review, Problems

#268 Moved filters to new component
  components/data/Filters.jsx
  pages/dashboard.js
Labels: Dashboard

#267 Removed console button
  components/Console.jsx
Labels: Ready for Review, Problems

#266 Removed submissions tab from problems
  components/ProblemStateToggle.jsx
  components/archive/ProblemSubmission.jsx
  pages/problems/[id].js
Labels: Ready for Review, Problems

#265 Populate Test Cases
  components/Console.jsx
  components/ProgrammingProblem.jsx
  components/TestCases.jsx
Labels: Ready for Review, Problems

#269 Jasmita y/add auth
  package-lock.json
  package.json
  pages/_app.js
  pages/api/auth/[...nextauth].js
Labels: Ready for Review

#270 Populate Solutions Tab
  components/ProblemSolution.jsx
  components/ProgrammingProblem.jsx
Labels: Ready for Review, Problems

#274 Login
  .eslintignore
  .gitignore
  .prettierignore
  components/CodeEditor.jsx
  components/Navigation.jsx
  components/ProblemRecord.jsx
  components/Profile.jsx
  components/ProtectedPage.jsx
  components/Welcome.jsx
  components/archive/ProblemSubmission.jsx
  components/archive/ProblemsSolved.jsx
  components/archive/Progress.jsx
  package-lock.json
  package.json
  pages/_app.js
  pages/api/auth/[...nextauth].js
  pages/api/getAttempts.js
  pages/dashboard.js
  pages/profile.js
  pages/signin.js
  pages/user/dashboard.js
  pages/user/problems/[id].js
  pages/user/profile.js
Labels: Repository

#281 Fix problem link
  components/ProgrammingProblem.jsx
Labels: Ready for Review, Problems

#273 Removed useEffect in testcases
  components/TestCases.jsx
Labels: Do Not Merge, Problems

#282 Made logo appear when not signed in
  components/Navigation.jsx
Labels: Ready for Review, Navigation

#284 Authenticate Update User Info
  pages/api/updateUserInfo.js
Labels: Ready for Review, Auth

#285 Seanquiambao/authenticate execute
  pages/api/execute.js
Labels: Auth

#283 Added authentication to getProblems
  pages/api/getProblems.js
Labels: Ready for Review, Auth

#292 added getProblem API Route
  pages/api/getProblem.js
Labels: Ready for Review, Problems

#294 Height Problem Page
  components/ProblemSolution.jsx
  pages/user/problems/[id].js
Labels: Ready for Review, Problems

#295 Fixed 404 and 500 rendering
  pages/404.js
  pages/500.js
Labels: Ready for Review, Navigation

#296 Removed firebase auth
  firebase.js
Labels: Ready for Review, Auth

#293 Pass Problems By Props
  components/Console.jsx
  components/ProblemDescription.jsx
  components/ProblemSolution.jsx
  components/TestCases.jsx
  pages/user/problems/[id].js
Labels: Ready for Review, Problems

#300 implemented the new users
  components/Profile.jsx
  pages/api/auth/[...nextauth].js
Labels: Sign Up, Ready for Review, Auth

#305 Remove problem context
  components/TestCases.jsx
  pages/_app.js
Labels: Ready for Review, Problems

#304 Redirecting /user to dashboard
  next.config.js
Labels: Ready for Review, Navigation

#311 Remove `setProblem` Context Reference
  components/ProgrammingProblem.jsx
Labels: Ready for Review, Problems

#315 Fixed logo href
  components/Navigation.jsx
Labels: Ready for Review, Navigation

#310 Removed Dashboard Context
  components/ProblemRecord.jsx
  pages/_app.js
  pages/user/dashboard.js
Labels: Dashboard, Ready for Review, Profile
