Repository acm-ucr/bitByBIT, pull requests merged in 2023-09, with the labels that each got.

#364 Make tags square
  components/Filter.jsx
Labels: Dashboard, Ready for Review

#365 Make Console Resizable
  components/Console.jsx
  components/TestCases.jsx
  package-lock.json
  package.json
  pages/user/problems/[id].js
Labels: Problems

#361 Removed constraints from problem description
  components/ProblemDescription.jsx
Labels: Ready for Review, Problems

#367 Changed navbar justification
  components/Navigation.jsx
Labels: Ready for Review, Navigation

#369 Made row items skinnier and aligned headers
  components/ProblemRecord.jsx
Labels: Ready for Review, Profile

#372 fix alternating problem colors
  components/Problems.jsx
  components/ProgrammingProblem.jsx
Labels: Dashboard, Ready for Review

#363 Display No Problems Found
  components/ProblemRecord.jsx
Labels: Ready for Review, Profile

#373 Fixed parsing tags errors on problem record and filters
  components/ProblemRecord.jsx
  pages/user/dashboard.js
Labels: Dashboard, Ready for Review, Profile

#356 Add States To Results
  components/Console.jsx
  components/Results.jsx
Labels: Ready for Review, Problems

#368 Only allow C++ to be selected
  components/CodeEditor.jsx
  components/data/Languages.jsx
  package-lock.json
  pages/_app.js
  pages/user/problems/[id].js
Labels: Ready for Review, Problems

#374 Removed 3 dots in dashboard
  components/Problems.jsx
Labels: Dashboard, Ready for Review

#375 Made test cases modular
  components/TestCases.jsx
Labels: Ready for Review, Problems

#378 Completed and In Progress Switch
  components/ProblemRecord.jsx
Labels: Profile

#376 Removed console logs
  components/Navigation.jsx
  components/Profile.jsx
Labels: Ready for Review, Repository

#377 Make Row Item Height Shorter
  components/ProgrammingProblem.jsx
Labels: Dashboard
