Repository acm-ucr/bitByBIT, pull requests merged in 2023-02, with the labels that each got.

#44 Search Component
  components/Search.jsx
Labels: Dashboard, Ready for Review

#46 Added Problems Solved Component #39
  components/ProblemsCategory.jsx
  components/ProblemsSolved.jsx
  pages/profile.js
Labels: Profile

#47 Add Submissions Component
  components/Submissions.jsx
Labels: Ready for Review, Profile

#49 34 destructure props in profile
  components/PrimaryLogo.jsx
  components/Profile.jsx
Labels: Ready for Review, Profile

#48 Add Random Button
  components/Search.jsx
Labels: Dashboard, Ready for Review

#50 Used Ternary Operator
  components/Problems.jsx
Labels: Ready for Review

#52 Problems Component Color Fix
  components/Problems.jsx
Labels: Dashboard, Ready for Review

#51 changed color for navbar 2.0
  components/Navigation.jsx
Labels: Ready for Review, Navigation

#63 Setup More Components
  components/ProblemDescription.jsx
  components/ProblemSolution.jsx
  components/ProblemStateToggle.jsx
  components/ProblemSubmission.jsx
  components/ProblemsSolved.jsx
  pages/problems.js
  pages/profile.js
Labels: Ready for Review

#67 Add Background on Problems
  pages/dashboard.js
Labels: Dashboard

#64 Create Filters component
  components/Filter.jsx
  components/Filters.jsx
Labels: Dashboard, Ready for Review

#70 Problem Solution Component
  components/ProblemSolution.jsx
Labels: Ready for Review, Problem

#66 500 page
  pages/500.js
Labels: Ready for Review

#65 404 page
  pages/404.js
Labels: Ready for Review, Repository

#71 fix tailwind color bug on Filters component
  components/Filter.jsx
  components/Filters.jsx
Labels: Dashboard

#74 Created Problem State Toggle
  components/ProblemSolution.jsx
  components/ProblemStateToggle.jsx
  pages/problems.js
Labels: Ready for Review, Problem

#73 Reduce Height to Fit Content
  components/Submissions.jsx
Labels: Ready for Review, Profile
