Repository acm-ucr/bitByBIT, pull requests merged in 2023-01, with the labels that each got.

#13 Setup Profile
  components/ProblemRecord.jsx
  components/ProblemsSolved.jsx
  components/Profile.jsx
  components/Submissions.jsx
  pages/profile.js
Labels: Ready for Review

#14 Implement Problems component with default colors
  components/Problems.jsx
Labels: Ready for Review

#17 Created Sign Up Confirmation Component
  components/SignUpConfirmation.jsx
Labels: Sign Up, Ready for Review

#24 Add Custom Colors
  tailwind.config.js
Labels: Ready for Review

#20 welcome components
  components/Welcome.jsx
  pages/index.js
Labels: Ready for Review

#19 Created Nav
  components/Navigation.jsx
  pages/index.js
Labels: Ready for Review

#26 Add readex font
  pages/_app.js
  tailwind.config.js
Labels: Ready for Review

#27 Layout
  components/Layout.jsx
  components/Navigation.jsx
  pages/_app.js
  pages/dashboard.js
  pages/index.js
  pages/profile.js
Labels: Ready for Review

#40 Added custom tailwind colors to Progress component
  components/Progress.jsx
Labels: Dashboard, Ready for Review

#42 Menthy/repo
  Dockerfile
  cloudbuild.yaml
  components/Welcome.jsx
  firebase.js
  package-lock.json
  package.json
Labels: Repository

#41 Added Figma colors to Problems component
  components/Problems.jsx
Labels: Dashboard

#45 Fixed Progress Scale
  components/Progress.jsx
Labels: Dashboard, Ready for Review
