Repository acm-ucr/bitByBIT, pull requests merged in 2023-06, with the labels that each got.

#246 Jasmita y/bit logo dash
  components/Console.jsx
  components/Navigation.jsx
  pages/_app.js
Labels: Ready for Review, Navigation

#244 changed default language to be C++
  pages/_app.js
Labels: Ready for Review, Problems

#243 populated attempts section
  components/ProblemRecord.jsx
  pages/_app.js
Labels: Ready for Review, Profile

#247 finished the id
  components/Problems.jsx
Labels: Ready for Review, Problems

#249 Increased Padding
  components/ProblemDescription.jsx
Labels: Ready for Review, Problems

#248 Remove console logs
  components/CodeEditor.jsx
  components/Console.jsx
Labels: Repository
